### ISSUE TITLE
java.lang.NoClassDefFoundError on right click on a project node

### ISSUE THREAD

**Issue by Chris2011** [Valery-Sh/jee-server-api#1]
When I right click on a project, doesn't matter which project, I got this exception.

```
java.lang.NoClassDefFoundError: org/netbeans/modules/jeeserver/base/deployment/utils/BaseUtil
	at org.netbeans.modules.jeeserver.jetty.project.nodes.actions.AddBeanXmlAction$ContextAction.<init>(AddBeanXmlAction.java:88)
	at org.netbeans.modules.jeeserver.jetty.project.nodes.actions.AddBeanXmlAction.createContextAwareInstance(AddBeanXmlAction.java:75)
	at org.openide.util.Utilities.actionsToPopup(Utilities.java:1719)
	at org.openide.util.Utilities.actionsToPopup(Utilities.java:1815)
	at org.openide.explorer.view.TreeView.createPopup(TreeView.java:1042)
	at org.openide.explorer.view.TreeView$PopupAdapter.showPopup(TreeView.java:1539)
	at org.openide.awt.MouseUtils$PopupMouseAdapter.maybePopup(MouseUtils.java:189)
	at org.openide.awt.MouseUtils$PopupMouseAdapter.mouseReleased(MouseUtils.java:184)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

This really depents me from using the plugin.

Regards

Chris

**Comment by Chris2011** [comment]
Using NetBeans 8.2 Patch 2

**Comment by Valery-Sh** [comment]
I'l publish in a month the new version of the plugin for Netbeans 8.1 and
8.2. The current version may not work with NetBeans 8.2

2017-06-16 15:46 GMT+03:00 Chrizzly <notifications@github.com>:

**Comment by Chris2011** [comment]
Great to hear that, thx :)
